[package]
name = "cukerust_wasm"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
regex = "1"
cukerust_core = { path = "../cukerust_core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
