name: ci
on:
  push:
  pull_request:

jobs:
  node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
      - name: Install deps
        working-directory: extension
        run: |
          npm ci || npm i
      - name: Build extension (WASM + TS)
        working-directory: extension
        run: npm run build

  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Rust tests
        run: cargo test --workspace --all-features --locked || cargo test --workspace
